### PR TITLE
refactor: check if git is installed in clone script

### LINKED ISSUE #90: Check if git is installed in script
Add a check to see if `git` is installed on the machine for the `clone:trpkit-materials` script.

### PR DESCRIPTION
**Pull request by Utkarsh3128**
## Description
Check if git is installed in script.

## Fixes #90

### CODE REVIEW

**Review by nsylke — CHANGES_REQUESTED** [review]
Thank you for the contribution! Could you run `pnpm run format`, otherwise it looks good to me!

**Comment by ghost** [comment]
Sure, I have run the command ```pnpm run format```

Screenshot (227)

Do I need to create another pull request?

**Comment by nsylke** [comment]
@Utkarsh3128 No, just push the changes from running the command - it just formats the code to keep it consistent.

**Comment by ghost** [comment]
I have push the changes. If any mistake please guide me.

**Review by nsylke — APPROVED** [review]
Looks good to me. Thank you for your contribution!

**Pull request merged**
